### ISSUE TITLE
Symfony 3/4 integration

### ISSUE THREAD

**Issue by scar-iat** [hipay/hipay-wallet-cashout-mirakl-integration#57]
Hi,

I have a rather dumb question here, since Silex was announced as dead (https://silex.symfony.com/), do you plan on adapting this integration to symfony 3/4 ?

Thanks

**Comment by jprotin** [comment]
Hi Samuel,

This connector is developped with Silex and we don't have a redesign project in the roadmap with sf3/4 yet.

many thank
